[package]
name = "emvpt"
version = "0.1.0"
authors = ["Mika Rautio"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]

[dependencies]
iso7816-tlv = "0.4.1"
hexplay = "0.2.1"
asn1_der = "0.7.2"
hex = "0.4.2"
serde = { version = "1.0.118", features = ["derive"] }
serde_yaml = "0.8.14"
log = "0.4.11"
log4rs = "1.0.0"
rand_chacha = "0.3.0"
rand = "0.8.0"
# NOTE: mingw pre built binaries here: https://bintray.com/vszakats/generic/openssl
openssl-sys = "0.9.59"
openssl = "0.10.31"
chrono = "0.4.19"