numeric_country_codes:
  '246': 'FI'
  '752': 'SE'
  '578': 'NO'
  '208': 'DK'
  '616': 'PL'
  '276': 'DE'
  '380': 'IT'
  '826': 'GB'
  '724': 'ES'
  '250': 'FR'
  '056': 'BE'
  '840': 'US'
  '356': 'IN'
  '643': 'RU'
  '156': 'CN'
  '756': 'CH'
  '392': 'JP'
  '036': 'AU'
numeric_currency_codes:
  '978': 'EUR'
  '826': 'GBP'
  '756': 'CHF'
  '752': 'SEK'
  '578': 'NOK'
  '208': 'DKK'
  '985': 'PLN'
  '840': 'USD'
  '123': 'CAD'
  '036': 'AUD'
  '156': 'CNY'
  '356': 'INR'
  '392': 'JPY'
  '643': 'RUB'