name: Update dependencies

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install -y libpcsclite-dev
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: cargo install cargo-edit cargo-audit
    - run: cd emvpt && cargo upgrade && cargo update && cargo audit && cargo test
    - run: cd terminalsimulator && cargo upgrade && cargo update && cargo audit && cargo test
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: Update dependencies
        commit-message: Update dependencies
        delete-branch: true
