[package]
name = "terminalsimulator"
version = "0.1.0"
authors = ["Mika Rautio"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
emvpt = { path = "../emvpt", version = "0.1.0" }
log = "0.4.11"
log4rs = "0.13.0"
clap = "2.33.3"
